services:
  nginx-service:
    image: nginx:latest
    container_name: nginx-latest
    ports:
      - 8000:80
    volumes:
      - ./../app:/var/www/html/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm-service
    networks:
      - oops-network
    profiles:
      - "development"
      - "testing"
      - "production"
  php-fpm-service:
    image: php:8.2-fpm
    container_name: php-fpm-latest
    working_dir: /var/www/html/app
    volumes:
      - ./../app:/var/www/html/app
    networks:
      - oops-network
    profiles:
      - "development"
      - "testing"
      - "production"
networks:
  oops-network:
# volumes:
# configs:
# secrets:
